version: "3"

services:
  # Builds Rome-EVM binary with selected parameters and deploys it
  rome-evm:
    container_name: rome-evm
    image: romelabs/rome-evm:${ROME_EVM_TAG:-latest}
    environment:
      SOLANA_RPC: ${SOLANA_RPC}
      CHAIN_ID: ${CHAIN_ID}
      ROME_EVM_KEYPAIR: /opt/rome-keypair.json
      CONTRACT_OWNER_KEYPAIR: /opt/rome-evm-owner.json
      MINT_TO: ${GENESIS_ADDRESS}
      MINT_AMOUNT: ${GENESIS_BALANCE}
    volumes:
      - ./rome-keypair.json:/opt/rome-keypair.json
      - ./rome-evm-owner.json:/opt/rome-evm-owner.json
    command: 'bash -c \ "/usr/bin/solana -u ${SOLANA_RPC} airdrop 100 /opt/rome-evm-owner.json \ && /opt/build.sh && /opt/deploy.sh && sleep 12 && /opt/initialize.sh"'
    networks:
      - net

  geth:
    container_name: geth
    image: romelabs/rollup-op-geth:${GETH_TAG:-latest}
    hostname: geth
    environment:
      CHAIN_ID: ${CHAIN_ID}
      GENESIS_ADDRESS: ${GENESIS_ADDRESS}
      GENESIS_BALANCE: ${GENESIS_BALANCE}
      GENESIS_PRIVATE_KEY: ${GENESIS_PRIVATE_KEY}
      GETH_HOST: ${GETH_HOST}
    volumes:
      - /etc/letsencrypt/live/${GETH_HOST}/fullchain.pem:/etc/nginx/ssl/selfsigned.crt
      - /etc/letsencrypt/live/${GETH_HOST}/privkey.pem:/etc/nginx/ssl/selfsigned.key
    ports:
      - 443:443
      - 8545:8545
      - 8546:8546
      - 8551:8551
      - 3000:3000
    networks:
      - net

  rhea:
    container_name: rhea
    image: romelabs/rome-apps:${RHEA_TAG:-latest}
    hostname: rhea
    environment:
      SERVICE_NAME: rhea
      RHEA_CONFIG: /opt/rhea-config.yml
    volumes:
      - ./rhea-config.yml:/opt/rhea-config.yml
      - ./rome-keypair.json:/opt/rome-keypair.json
      - ./rhea-sender.json:/opt/rhea-sender.json
    networks:
      - net
    depends_on:
      geth:
        condition: service_started

  light_client:
    container_name: light_client
    image: romelabs/rome-apps:${PROXY_TAG:-latest}
    hostname: light_client
    environment:
      SERVICE_NAME: proxy
      PROXY_CONFIG: /opt/proxy-config.yml
    volumes:
      - ./proxy-config.yml:/opt/proxy-config.yml
      - ./rome-keypair.json:/opt/rome-keypair.json
      - ./proxy-sender.json:/opt/proxy-sender.json
    ports:
      - 9090:9090
    expose:
      - "9090"
    networks:
      - net

networks:
  net:
