version: "3"

services:
  # Solana validator
  solana:
    container_name: solana
    image: romeprotocol/test-validator:latest
    environment:
      RUST_LOG: solana_runtime::system_instruction_processor=debug,solana_runtime::message_processor=debug,solana_bpf_loader=debug,solana_rbpf=debug
    hostname: solana
    ports:
      - 8899:8899
      - 9900:9900
      - 8900:8900
      - 8003:8003/udp
    expose:
      - "8899"
      - "9900"
      - "8900"
      - "8001"
      - "8001-8009/udp"
    networks:
      - net
    healthcheck:
      test: [ CMD-SHELL, "solana cluster-version -u http://solana:8899" ]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 10s

  proxy:
    container_name: proxy
    image: romeprotocol/rome-apps:${PROXY_TAG:-latest}
    hostname: proxy
    environment:
      SERVICE_NAME: proxy
      PROXY_CONFIG: /opt/proxy-config.yml
      TEST_MODE: True
    volumes:
      - ./proxy-config.yml:/opt/proxy-config.yml
      - ./rome-keypair.json:/opt/rome-keypair.json
      - ./proxy-sender.json:/opt/proxy-sender.json
    ports:
      - 9090:9090
    networks:
      - net
    depends_on:
      solana:
        condition: service_healthy

  uniswap-v2-core:
    container_name: uniswap
    image: romeprotocol/uniswap-v2-core:latest
    environment:
      NETWORK: proxy
      CHAIN_ID: 1001
    depends_on:
      proxy:
        condition: service_started
    networks:
      - net
    entrypoint: yarn test

networks:
  net:
