name: Manual Push to Docker Hub No Tests

on:
  workflow_dispatch:
    inputs:
      rome_evm_ref_name:
        type: string
        description: 'rome_evm branch name to use for building the image'
        required: false
        default: 'main'
      rome_sdk_ref_name:
        type: string
        description: 'rome_sdk branch name to use for building the image'
        required: false
        default: 'main'

jobs:
  prepare_env:
    runs-on: ubuntu-latest
    steps:
      - name: Set Outputs
        id: set_outputs
        run: |
          echo "rome_evm_ref_name=${{ github.event.inputs.rome_evm_ref_name }}" >> $GITHUB_ENV
          echo "rome_sdk_ref_name=${{ github.event.inputs.rome_sdk_ref_name }}" >> $GITHUB_ENV
          echo "rome_apps_ref_name=${{ github.ref_name }}" >> $GITHUB_ENV
          echo "::set-output name=rome_evm_ref_name::${{ github.event.inputs.rome_evm_ref_name }}"
          echo "::set-output name=rome_sdk_ref_name::${{ github.event.inputs.rome_sdk_ref_name }}"
          echo "::set-output name=rome_apps_ref_name::${{ github.ref_name }}"
    outputs:
      rome_evm_ref_name: ${{ steps.set_outputs.outputs.rome_evm_ref_name }}
      rome_sdk_ref_name: ${{ steps.set_outputs.outputs.rome_sdk_ref_name }}
      rome_apps_ref_name: ${{ steps.set_outputs.outputs.rome_apps_ref_name }}

  reusable-wf-build:
    uses: ./.github/workflows/reusable_wf_build.yml
    needs: prepare_env
    secrets: inherit
    with:
      rome_evm_ref_name: ${{ needs.prepare_env.outputs.rome_evm_ref_name }}
      rome_sdk_ref_name: ${{ needs.prepare_env.outputs.rome_sdk_ref_name }}
      rome_apps_ref_name: ${{ needs.prepare_env.outputs.rome_apps_ref_name }}
