name: build_images

on:
  push:
  workflow_dispatch:

env:
  REF_NAME: ${{github.ref_name}}
  ROME_SDK_REF_NAME: v0.1.0
  ROME_EVM_REF_NAME: v0.1.0

permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Compose
        uses: ndeloof/install-compose-action@v0.0.1
        with:
          version: v2.1.0 # defaults to 'latest'
          legacy: true    # will also install in PATH as `docker-compose`

      - name: Check Docker Compose version
        run: docker-compose --version

      - name: 'Checkout rome-evm repository'
        uses: actions/checkout@main
        with:
          repository: rome-protocol/rome-evm-private
          path: rome-evm-private
          ref: ${{env.ROME_EVM_REF_NAME}}
          token: ${{ secrets.GIT_ROLLUP_TOKEN }}

      - name: 'Checkout rome-sdk repository'
        uses: actions/checkout@main
        with:
          repository: rome-protocol/rome-sdk
          path: rome-sdk
          ref: ${{env.ROME_SDK_REF_NAME}}
          token: ${{ secrets.GIT_ROLLUP_TOKEN }}

      - name: 'Checkout rome-apps repository'
        uses: actions/checkout@v4
        with:
          path: rome-apps
          token: ${{ secrets.GIT_ROLLUP_TOKEN }}

      - name: 'Login to Docker Hub'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: 'Build rome-apps image'
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          push: true
          file: rome-apps/docker/Dockerfile
          tags: romeprotocol/rome-apps:${{env.REF_NAME}}
          labels: romeprotocol/rome-apps:${{env.REF_NAME}}

      - name: 'Up Uniswap-v2-core tests'
        run: |
          set +e
          export PROXY_TAG=${{env.REF_NAME}} RHEA_TAG=${{env.REF_NAME}}
          docker-compose -f rome-apps/docker/docker-compose-ci.yml up uniswap-v2-core --exit-code-from uniswap-v2-core
          echo "UNISWAP_EXIT_CODE=$?" >> $GITHUB_ENV
        continue-on-error: true

      - name: 'Dump docker logs'
        uses: jwalton/gh-docker-logs@v2
        with:
          dest: './logs'

      - name: 'Tar logs'
        run: tar cvzf ./logs.tgz ./logs

      - name: Upload logs to GitHub
        uses: actions/upload-artifact@master
        with:
          name: logs.tgz
          path: ./logs.tgz

      - name: 'Down docker-compose'
        run: docker-compose -f rome-apps/docker/docker-compose-ci.yml down --rmi all -v

      - name: 'Check test results'
        run: |
          if [ $UNISWAP_EXIT_CODE -ne 0 ]; then
            echo "uniswap-v2-core failed. Exiting."
            exit 1
          fi

      - name: 'Set latest tag'
        if: |
          ( github.ref_name == 'main' )
        run: |

          docker pull romeprotocol/rome-apps:${REF_NAME}
          docker tag romeprotocol/rome-apps:${REF_NAME} romeprotocol/rome-apps:latest
          docker push romeprotocol/rome-apps:latest
